### ISSUE TITLE
Função para converter valores px para rem

### ISSUE THREAD

**Issue by lucianobarauna** [Yoonit-Labs/sass-yoonit-style#68]
Existe desenvolvedores que preferem trabalhar com a medida `rem` então em cima disso estou abrindo essa sugestão para implementação na lib.

A função consiste em já ter um valor base que é definido por padrão na configuração e esse valor é utilizado para realizar a conversão da fonte px para rem.

### Exemplo de valor base utilizando a configuração global:

```
body {
  font-size: pxToRem(16) // font-size: 1rem;
}

.foo {
    font-size: pxToRem(16, 14) // font-size: 1.14286rem;
}

```
### Exemplo de valor base customizado:
Nesse caso está sendo solicitado o valor de `16` mas sendo convertido com a base de `14` definida nesse ponto.

```
.foo {
  font-size: pxToRem(16, 14) // font-size: 1.14286rem;
}
```

**Comment by luiguild** [comment]
LGTM
